### PR TITLE
Enum support for pin_project! macro

### PR DESCRIPTION
**Pull request by taiki-e**
Like pin-project, by passing an argument with the same name as the method to the attribute, you can name the projection type returned from the method. This allows you to use pattern matching on the projected types.

```rust
use pin_project_lite::pin_project;
use std::pin::Pin;

pin_project! {
    // The `#[project]` (and `#[project_ref]`) attribute must precede the other attributes except for `#[doc]`:
    #[project = EnumProj] 
    #[project_ref = EnumProjRef]
    #[derive(Debug)]
    enum Enum<T, U> {
        Struct {
            #[pin]
            pinned: T,
            unpinned: U,
        },
        Unit,
    }
}

impl<T, U> Enum<T, U> {
    fn method(self: Pin<&mut Self>) {
        match self.project() {
            EnumProj::Struct { pinned, unpinned } => {
                let _: Pin<&mut T> = pinned;
                let _: &mut U = unpinned;
            }
            EnumProj::Unit => {}
        }
    }
}
```

Also, this does not provide support to tuple variants for the same reason that it does not support tuple structs.

### CODE REVIEW

**Comment by taiki-e** [comment]
I'm wondering what syntax is preferable, so I would appreciate any feedback.

**Comment by stjepang** [comment]
What if the attribute syntax was used, similar to the one in pin-project?

So perhaps something like `#[project = EnumProj]` above the enum definition.

**Comment by taiki-e** [comment]
Ah, that looks like a good idea. There may be a limitation like #3, but I'll try it.

**Comment by stjepang** [comment]
It's okay if there are a few limitations with known workarounds. I think it's amazing that you managed to pull this off at all without procedural macros :)

**Comment by taiki-e** [comment]
I think the implementation is basically complete, but I'll look into limitations and minor bugs before the merge.

**Comment by taiki-e** [comment]
Filed #36 to track diagnostics issues. I'm going to merge this.

bors r+

**Comment by taiki-e** [comment]
Published in 0.2.0.

**Pull request merged**
